#!/usr/bin/env bash
# install nginx web server and create html pages
apt-get -y update
apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
