#!/usr/bin/env bash
# install nginx web server and create html pages
sudo apt-get -y update
sudo apt-get install -y nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
